words_list = ["Hakuna Matata",
              "junk",
              "lovely",
              "Jasari",
              "jahsiyah",
              "Naruto",
              "luffy",
              "Programmer",
              "coding",
              "Revenge",
              "money",
              "Turkey",
              "Snowfall",
              "Abstinence",
              "fasting",
              "Power",
              "Telepathy",
              "son of man",
              "Allah",
              "muslim",
              "love"]